name: BungeePortals
version: 1.2
description: Create portals of any shape or size with WorldEdit, for BungeeCord.
author: YoFuzzy3
main: net.yofuzzy3.BungeePortals.BungeePortals
dev-url: http://www.spigotmc.org/resources/bungeeportals.19/
softdepend: [WorldEdit]

commands:
    BPortals:
        description: Do cool stuff.
permissions:
    BungeePortals.command.BPortals:
        description: Allowed to access the command /BPortals.
        default: op
    BungeePortals.portal.*:
        description: Access to all portals.
        default: true